package studentmanagementsystem.menu;

import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import studentmanagementsystem.ConnectDB;
import studentmanagementsystem.managers.ItemManager;
import studentmanagementsystem.SanitizeInputs;
import studentmanagementsystem.managers.UserManager;
import static studentmanagementsystem.menu.createStudentMenu.resize;

/**
 *
 * @author tuc02096
 */
public class editStudentMenu extends javax.swing.JFrame {
    private String editState;
    private String fileName;
    ImageIcon icon = null;
    /**
     * Creates new form editStudentMenu
     */
    public editStudentMenu() {
        initComponents();
        editState = "";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cancelBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        firstNameRadioBtn = new javax.swing.JRadioButton();
        lastNameRadioBtn = new javax.swing.JRadioButton();
        dobRabioBtn = new javax.swing.JRadioButton();
        addressRadioBtn = new javax.swing.JRadioButton();
        phoneRadioBtn = new javax.swing.JRadioButton();
        emailRadioBtn = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        firstNameTxtField = new javax.swing.JTextField();
        lastNameTxtField = new javax.swing.JTextField();
        studentIDTxtField = new javax.swing.JTextField();
        editTxtField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pictureRadioBtn = new javax.swing.JRadioButton();
        editPictureLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Edit Student");

        cancelBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        editBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        editBtn.setText("Save");
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        firstNameRadioBtn.setText("First Name");
        firstNameRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameRadioBtnActionPerformed(evt);
            }
        });

        lastNameRadioBtn.setText("Last Name");
        lastNameRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameRadioBtnActionPerformed(evt);
            }
        });

        dobRabioBtn.setText("Date of Birth");
        dobRabioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dobRabioBtnActionPerformed(evt);
            }
        });

        addressRadioBtn.setText("Address");
        addressRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressRadioBtnActionPerformed(evt);
            }
        });

        phoneRadioBtn.setText("Phone");
        phoneRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneRadioBtnActionPerformed(evt);
            }
        });

        emailRadioBtn.setText("Email");
        emailRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailRadioBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("Enter student's first name + last name or student ID");

        jLabel3.setText("and the field which you would like to modify");

        jLabel4.setText("First Name:");

        jLabel5.setText("Last Name:");

        jLabel6.setText("Student ID:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Student:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Edit Field:");

        pictureRadioBtn.setText("Picture");
        pictureRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pictureRadioBtnActionPerformed(evt);
            }
        });

        editPictureLbl.setText("         Student Picture");
        editPictureLbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255), 3));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel3))
                            .addComponent(jLabel2)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(jLabel1)
                                .addGap(85, 85, 85))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(2, 2, 2)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addGap(18, 18, 18)
                                            .addComponent(lastNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel7)
                                                .addComponent(firstNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGap(18, 18, 18)
                                    .addComponent(studentIDTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dobRabioBtn)
                                    .addComponent(firstNameRadioBtn)
                                    .addComponent(phoneRadioBtn)
                                    .addComponent(editTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(emailRadioBtn)
                                    .addComponent(addressRadioBtn)
                                    .addComponent(lastNameRadioBtn)))
                            .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editPictureLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pictureRadioBtn))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(editPictureLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pictureRadioBtn)
                        .addContainerGap(106, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(firstNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(lastNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(studentIDTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(editTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(firstNameRadioBtn)
                                    .addComponent(lastNameRadioBtn))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(dobRabioBtn)
                                    .addComponent(addressRadioBtn))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(phoneRadioBtn)
                                    .addComponent(emailRadioBtn))))
                        .addGap(140, 140, 140))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        Item item = new Item();
        item.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        int areYouSure = JOptionPane.showConfirmDialog(null, "Are you sure you want to edit the specified user?");
        if (areYouSure == 0){
            boolean pictureChecksum = false;
            String tempIDString = SanitizeInputs.removeNonDigitFromIDString(studentIDTxtField.getText());
            int studentID = (tempIDString.equals("")) ? 0 : Integer.parseInt(studentIDTxtField.getText());
            String firstName = SanitizeInputs.sanitizeInputString(firstNameTxtField.getText());
            String lastName = SanitizeInputs.sanitizeInputString(lastNameTxtField.getText());
            String editText = SanitizeInputs.sanitizeInputString(editTxtField.getText());
            if ((studentID > 0) || ((!firstName.equals("")) && (!lastName.equals("")))){
                String sql = "update students set ";
                if (!editState.equals("")){
                    switch(editState){
                        case "first name":
                            sql = sql+"first_name = '";
                            break;
                        case "last name":
                            sql = sql+"last_name = '";
                            break;
                        case "dob":
                            sql = sql+"dob = '";
                            break;
                        case "address":
                            sql = sql+"address = '";
                            break;
                        case "phone":
                            sql = sql+"phone = '";
                            break;
                        case "email":
                            sql = sql+"email = '";
                            break;
                        case "picture":
                            pictureChecksum = true;
                            sql = "";
                    }
                    if (pictureChecksum == false){
                        if (studentID > 0){
                            sql = ((!firstName.equals("") && (!lastName.equals("")))) ?
                                    sql + editText + "' where student_id = "+studentID
                                    +" and upper(first_name) = upper('"+firstName+"') and "
                                    +"upper(last_name) = upper('"+lastName+"')" :
                                    sql + editText + "' where student_id = "+studentID;
                        }
                        else{
                            sql = sql + editText + "' where upper(first_name) = upper('"
                                    +firstName+"') and upper(last_name) = upper('"
                                    +lastName+"')";
                        }
                        try{
                            UserManager.executeQuery(sql);
                            Item item = new Item();
                            item.setVisible(true);
                            setVisible(false);
                        }catch (SQLException ex) {
                            Logger.getLogger(deleteStudentMenu.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                    else{
                        if (icon != null){
                            Connection conn = null;
                            ResultSet rs = null;
                            try{
                                conn = ConnectDB.getConnection();
                                boolean photoPresent;
                                if (studentID > 0){
                                    photoPresent = ItemManager.checkIfPhotoPresent(studentID);
                                    // if photo present
                                    if (true == photoPresent){
                                        try (PreparedStatement pstmt = conn.prepareStatement("update student_photo set picture = ? where student_id = ?")) {
                                            FileInputStream fis = new FileInputStream(fileName);
                                            pstmt.setBinaryStream(1, fis, (int)fileName.length()); 
                                            pstmt.setInt(2, studentID);
                                            pstmt.executeUpdate();
                                        }
                                    }
                                    else{
                                        try (PreparedStatement pstmt = conn.prepareStatement("insert into student_photo (student_id, picture) values (?, ?)")){
                                            File file = new File(fileName);
                                            FileInputStream fis = new FileInputStream(file);
                                            pstmt.setInt(1, studentID);
                                            pstmt.setBinaryStream(2, fis, (int)file.length()); 
                                            pstmt.executeQuery();
                                        }
                                    }
                                    conn.commit();
                                    conn.close();
                                }
                                else{
                                    // we have to find the student ID because the studentID
                                    // is the foreign key used to connect the student
                                    // table and student_photo table
                                    sql = "select student_id from students where first_name = '"
                                        +firstName+"' and last_name = '" + lastName + "'";
                                        rs = ItemManager.getSearchItems(sql);
                                        if (rs.next()){
                                            studentID = rs.getInt("student_id");
                                            photoPresent = ItemManager.checkIfPhotoPresent(studentID);
                                            if (true == photoPresent){
                                                try (PreparedStatement pstmt = conn.prepareStatement("update student_photo set picture = ? where student_id = ?")) {
                                                    File file = new File(fileName);
                                                    FileInputStream fis = new FileInputStream(file);
                                                    pstmt.setBinaryStream(1, fis, (int)file.length()); 
                                                    pstmt.setInt(2, studentID);
                                                    pstmt.executeUpdate();
                                                }
                                            }
                                            else{
                                                try (PreparedStatement pstmt = conn.prepareStatement("insert into student_photo (student_id, picture) values (?, ?)")){
                                                    File file = new File(fileName);
                                                    FileInputStream fis = new FileInputStream(file);
                                                    pstmt.setInt(1, studentID);
                                                    pstmt.setBinaryStream(2, fis, (int)file.length()); 
                                                    pstmt.executeQuery();
                                                }
                                            }
                                            conn.commit();
                                            conn.close();
                                        }
                                }                            
                            }catch ( SQLException | FileNotFoundException ex) {
                                    Logger.getLogger(editStudentMenu.class.getName()).log(Level.SEVERE, null, ex);
                            }
                            finally{
                                if (rs != null)
                                    rs = null;
                                if (conn != null)
                                    conn = null;
                                Item item = new Item();
                                item.setVisible(true);
                                setVisible(false);
                            }
                        }
                    }
                }
                else
                    JOptionPane.showMessageDialog(null, "Select a field you would like to modify");
            }
            else{
                JOptionPane.showMessageDialog(null, "Must enter either a student ID or first name+last name");
            }
        }
    }//GEN-LAST:event_editBtnActionPerformed
   
    private void firstNameRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameRadioBtnActionPerformed
        editState = "first name";
    }//GEN-LAST:event_firstNameRadioBtnActionPerformed

    private void lastNameRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameRadioBtnActionPerformed
        editState = "last name";
    }//GEN-LAST:event_lastNameRadioBtnActionPerformed

    private void dobRabioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dobRabioBtnActionPerformed
        editState = "dob";
    }//GEN-LAST:event_dobRabioBtnActionPerformed

    private void addressRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressRadioBtnActionPerformed
        editState = "address";
    }//GEN-LAST:event_addressRadioBtnActionPerformed

    private void phoneRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneRadioBtnActionPerformed
        editState = "phone";
    }//GEN-LAST:event_phoneRadioBtnActionPerformed

    private void emailRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailRadioBtnActionPerformed
        editState = "email";
    }//GEN-LAST:event_emailRadioBtnActionPerformed

    private void pictureRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pictureRadioBtnActionPerformed
        editState = "picture";
        final JFileChooser fc = new JFileChooser();
        int returnVal = fc.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            fileName = file.getAbsolutePath();
            fileName = fileName.replaceAll("\\\\\\\\", "\\\\");
            fileName = fileName.replace("C:\\", "C:\\\\");
            try {
                BufferedImage image = ImageIO.read(file);
                BufferedImage resizedImage=resize(image,143,143);
                icon = new ImageIcon(resizedImage);
            } catch (IOException ex) {
                Logger.getLogger(createStudentMenu.class.getName()).log(Level.SEVERE, null, ex);
            }
            editPictureLbl.setIcon(icon);
        }
    }//GEN-LAST:event_pictureRadioBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton addressRadioBtn;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JRadioButton dobRabioBtn;
    private javax.swing.JButton editBtn;
    private javax.swing.JLabel editPictureLbl;
    private javax.swing.JTextField editTxtField;
    private javax.swing.JRadioButton emailRadioBtn;
    private javax.swing.JRadioButton firstNameRadioBtn;
    private javax.swing.JTextField firstNameTxtField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton lastNameRadioBtn;
    private javax.swing.JTextField lastNameTxtField;
    private javax.swing.JRadioButton phoneRadioBtn;
    private javax.swing.JRadioButton pictureRadioBtn;
    private javax.swing.JTextField studentIDTxtField;
    // End of variables declaration//GEN-END:variables
}
